---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Services:
  - Pi-hole:
      href: http://192.168.178.97/admin
      description:
      widget:
        type: pihole
        url: http://192.168.178.97
        version: 6
        key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
  - Speedtest Tracker:
      href: http://192.168.178.97:1080
      description:
      server: local-docker
      container: speedtest-tracker
      widget:
        type: speedtest
        url: http://192.168.178.97:1080
  - FreshRSS:
      href: http://192.168.178.97:2080
      description:
      server: local-docker
      container: freshrss
      widget:
        type: freshrss
        url: http://192.168.178.97:2080
        username: jamie
        password: {{HOMEPAGE_VAR_FRESHRSS_API_KEY}}
  - Finances:
      href: http://192.168.178.97:3080
      description:
      server: local-docker
      container: finances
  - Octograph:
      href: http://192.168.178.97:3001/d/da368873-f72e-4dd9-a3d5-01a84cff98d8/energy-usage?orgId=1
      description:
      server: local-docker
      container: octograph-grafana-1

- Diskstation:
  - Audio:
      href: http://diskstation.local/audio
      description: Audio Station
  - Download:
      href: http://diskstation.local/download
      description: Download Station
  - Drive:
      href: http://diskstation.local/drive
      description: Drive
  - Files:
      href: http://diskstation.local/file
      description: File Station
  - Photos:
      href: http://diskstation.local/photo
      description: Photos

- Admin:
  - Primary router:
      href: http://192.168.178.1
      description: FRITZ!Box 7530
  - Secondary router:
      href: http://192.168.178.100
      description: NETGEAR AP WAC104
  - Printer:
      href: http://192.168.178.27/
      description: M283x Series
  - Battery:
      href: http://192.168.178.20
      description: Puredrive nanopi
